/**
 * This code was generated by Builder.io.
 */

const Navbar = () => (
  <div className="flex gap-5 justify-between self-center w-full max-w-[1702px] max-md:flex-wrap max-md:max-w-full">
    <div className="flex gap-3 my-auto text-xl tracking-tight leading-7 whitespace-nowrap text-neutral-900">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/91c4a65cd79a72b2a0bb1da2c4a4e973d9b9ce4ce2eac3544f6b9ad9c91023a2?apiKey=038a4735f86746288acce602b4881da8&" className="w-16 aspect-[2.22]" alt="Company Logo" />
      <span className="grow my-auto">UNDETECTABLE.AI</span>
    </div>
    <div className="flex gap-1 justify-between items-center max-md:flex-wrap max-md:max-w-full">
      <div className="flex overflow-hidden relative flex-col justify-center self-stretch aspect-[2.4] w-[125px]">
        <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/966ea8ff-92af-4a7a-bf6c-7e7c3d253882?apiKey=038a4735f86746288acce602b4881da8&" className="object-cover absolute inset-0 size-full" alt="Product Thumbnail" />
        <div className="relative shrink-0 rounded-md border border-solid bg-zinc-100 border-neutral-900 border-opacity-0 h-[52px]" />
      </div>
      <span className="self-stretch my-auto text-xl tracking-tight leading-7 text-neutral-900 text-opacity-70">ChatPDF</span>
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/fbfe612722223bd29158014e0a994cdecee5b5de777cb2dc0adda28ff705d868?apiKey=038a4735f86746288acce602b4881da8&" className="self-stretch my-auto w-2.5 aspect-square" alt="" />
      <span className="flex-auto self-stretch my-auto text-xl tracking-tight leading-7 text-neutral-900 text-opacity-70">Business Solutions</span>
      <span className="self-start text-base tracking-tight leading-5 text-red-600 text-opacity-70">NEW</span>
      <span className="grow self-stretch my-auto text-xl tracking-tight leading-7 text-neutral-900 text-opacity-70">Documents</span>
    </div>
    <div className="flex gap-1 justify-between self-start text-xl tracking-tight leading-7 whitespace-nowrap text-neutral-900 text-opacity-70">
      <span className="grow self-end mt-7">Pricing</span>
      <span className="self-start text-base tracking-tight text-red-600 text-opacity-70">SALE</span>
      <span className="my-auto">API</span>
      <span className="my-auto">Earn</span>
      <div className="rounded-full bg-neutral-900 h-[50px] w-[50px]" />
    </div>
  </div>
);

const PDFViewer = () => (
  <section className="flex flex-col w-[34%] max-md:ml-0 max-md:w-full">
    <div className="flex flex-col self-stretch my-auto text-base tracking-tight leading-6 text-center whitespace-nowrap text-neutral-900 max-md:mt-10 max-md:max-w-full">
      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/5e1822de02f7f26967ecd512bf7d150ca72d9fd710de7cb1b373aed2fb7c7ff9?apiKey=038a4735f86746288acce602b4881da8&" className="w-full aspect-[0.81] max-md:max-w-full" alt="PDF Content Preview" />
      <div className="flex gap-5 justify-between pr-2 mt-3.5 w-full max-md:flex-wrap max-md:max-w-full">
        <div className="flex gap-1.5 justify-between">
          <div className="justify-center items-center px-2 h-5 rounded-md aspect-square bg-neutral-900 bg-opacity-10">1</div>
          <span className="self-start mt-1.5">/14</span>
        </div>
        <div className="flex gap-5 justify-between">
          <span className="my-auto">100%</span>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/eccae681179793131cd4f2fe43edd7627cde0cb5a51e97ba0c7e8aa0f139952a?apiKey=038a4735f86746288acce602b4881da8&" className="w-5 aspect-square" alt="Zoom In" />
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/1ef64675385bc6bc984241fc6691c8d8651cf728dcee2e807377f1e9a3bce89f?apiKey=038a4735f86746288acce602b4881da8&" className="w-5 aspect-square" alt="Zoom Out" />
        </div>
      </div>
    </div>
  </section>
);

const ContentArea = () => (
  <section className="flex flex-col ml-5 w-[49%] max-md:ml-0 max-md:w-full">
    <div className="flex flex-col grow py-8 w-full bg-neutral-900 rounded-[30px] max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col px-8 max-md:px-5 max-md:max-w-full">
        <div className="flex gap-5 justify-between w-full max-md:flex-wrap max-md:max-w-full">
          <article className="grow justify-center px-9 py-12 text-base tracking-tight leading-6 underline bg-zinc-100 rounded-[30px_30px_0px_30px] text-neutral-900 max-md:px-5 max-md:max-w-full">
            Welcome to the PDF file, "Smart Watch User Guide"! This document was created to guide users on how to use and set up the smartwatch. Example questions:<br />
            <span className="underline text-neutral-900">Which phones are compatible with my hybrid smartwatch?</span><br />
            <span className="underline text-neutral-900">How do I set up my device?</span><br />
            <span className="underline text-neutral-900">What comes with my hybrid smartwatch?</span>
          </article>
          <div className="flex gap-5 self-start">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/b684ca8f699a1e005f9591484496c2f3a191d274be0a0ab2a62641ecfb328a96?apiKey=038a4735f86746288acce602b4881da8&" className="aspect-square w-[30px]" alt="Icon Placeholder" />
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/730d5c37c595065817f815d8d6700190df872d7c5c489e5af2526870083bf9bc?apiKey=038a4735f86746288acce602b4881da8&" className="aspect-square w-[30px]" alt="Icon Placeholder" />
          </div>
        </div>
        <div className="justify-center self-end px-16 py-6 mt-8 text-base tracking-tight leading-6 whitespace-nowrap bg-zinc-100 bg-opacity-10 rounded-[30px_30px_0px_30px] text-zinc-100 max-md:px-7 max-md:max-w-full">
          Which phones are compatible with my hybrid smartwatch?
        </div>
      </div>
      <div className="flex flex-col px-8 mt-8 text-base tracking-tight max-md:px-5 max-md:max-w-full">
        <div className="justify-center px-9 py-11 leading-6 underline bg-zinc-100 rounded-[30px_30px_0px_30px] text-neutral-900 max-md:px-5 max-md:max-w-full">
          Your hybrid smartwatch is compatible with Android(TM) phones and iPhone(R), specifically with Android OS 4.4 or higher, iOS 8.1/iPhone 5 and above. All devices are Bluetooth(R) enabled with an improved data transfer of 4.1 Low Energy.<br /><br />
          Source: <span className="underline text-neutral-900">p. 1</span>
        </div>
        <div className="flex gap-2.5 justify-between mt-20 text-center whitespace-nowrap leading-[150%] text-zinc-600 text-opacity-50 max-md:flex-wrap max-md:mt-10 max-md:max-w-full">
          <div className="grow justify-center items-start px-8 py-6 border border-solid border-zinc-100 rounded-[30px] max-md:px-5 max-md:max-w-full">
            Ask any question
          </div>
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/43e278ad80b65c2e1ec45ac06a573e9b509f1fb96c39d7bb14b85cac50ab3182?apiKey=038a4735f86746288acce602b4881da8&" className="aspect-square w-[65px]" alt="Microphone Icon" />
        </div>
      </div>
    </div>
  </section>
);

const Dashboard = () => (
  <main className="flex flex-col px-7 py-11 bg-zinc-100 max-md:px-5">
    <Navbar />
    <div className="mt-10 max-md:max-w-full flex gap-5 max-md:flex-col max-md:gap-0">
      <aside className="flex flex-col w-[17%] max-md:ml-0 max-md:w-full">
        {/* Placeholder for Sidebar Widgets */}
      </aside>
      <PDFViewer />
      <ContentArea />
    </div>
  </main>
);

export default Dashboard;